name: wikiwho-demo-environment
channels:
  - conda-forge
dependencies:
  - python=>3.6
  - numpy
  - pandas==0.25.3
  - jupyter
  - pip:
    - wordcloud
    - nbstripout
    - wikiwho_wrapper
    - ipywidgets==7.4.2
    - matplotlib
    - plotly
    - qgrid
    - multidict
    - jupyter_contrib_nbextensions
    - keyboard
    - tqdm
    - pyLDAvis
    - sklearn
